CREATE TABLE IF NOT EXISTS `marketplace_stock` (
  `id_toko` VARCHAR(50) NOT NULL,
  `nama_item` VARCHAR(100) NOT NULL,
  `stok` INT NOT NULL DEFAULT 0,
  `diupdate_pada` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_toko`, `nama_item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
